language: python
python:
  - 3.6
  - 3.5

services:
  - mongodb

before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Generate PYPI package on tagged versions on master
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user:
    secure: ${PYPI_USER}
  password:
    secure: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/oceandb-mongodb-driver
    python: 3.6
